# QUERY1:

Display the crew percentage for any picture type according to the range of years. (range of year and picture type will be selected by the user)

SELECT M.CATEGORY,ROUND(((M.NCOUNT/M.Total)*100), 2) AS PERCENT FROM
(SELECT P.CATEGORY,COUNT(P.NCONST)AS NCOUNT,SUM(COUNT(P.NCONST)) OVER() AS Total
FROM PRINCIPAL_CREWINFO P JOIN
(SELECT TCONST,STARTYEAR,TITLETYPE
FROM TITLE_INFORMATION
WHERE STARTYEAR>'$from'
AND STARTYEAR<'$to'
AND TITLETYPE='$titletype') T
ON T.TCONST=P.TCONST
GROUP BY P.CATEGORY) M

# QUERY2:

Here is the data for a line graph where tv series are grouped according to the start year, number of seasons, max rating received showing a trend for ratings received for the year 1990-2004 for tv series with respective number of seasons. User can select the number of seasons and the year range.

SELECT M1.SY1,M1.S1,M1.MAX_RATING_1,M2.SY2,M2.S2,M2.MAX_RATING_2,M3.SY3,M3.S3,M3.MAX_RATING_3,
M4.SY4,M4.S4,M4.MAX_RATING_4,M5.SY5,M5.S5,M5.MAX_RATING_5,M6.SY20,M6.S20,M6.MAX_RATING_20 FROM
(SELECT T.STARTYEAR AS SY1,B.SEASONS AS S1,ROUND(MAX(RATING),2) AS MAX_RATING_1,ROW_NUMBER() OVER(ORDER BY T.STARTYEAR ASC) AS rn 
FROM (SELECT A.SEASONS,A.T_ID,R.AVERAGERATING AS RATING FROM
(SELECT PARENTTCONST AS T_ID,COUNT(SEASONNUMBER)AS SEASONS
FROM EPISODE_INFORMATION
GROUP BY PARENTTCONST) A,RATINGS R
WHERE A.T_ID=R.TCONST) B,
TITLE_INFORMATION T
WHERE B.T_ID=T.TCONST
AND B.SEASONS=1
GROUP BY T.STARTYEAR,B.SEASONS) M1,
(SELECT T.STARTYEAR AS SY2,B.SEASONS S2,ROUND(MAX(RATING),2) AS MAX_RATING_2,ROW_NUMBER() OVER(ORDER BY T.STARTYEAR ASC) AS rn  
FROM (SELECT A.SEASONS,A.T_ID,R.AVERAGERATING AS RATING FROM
(SELECT PARENTTCONST AS T_ID,COUNT(SEASONNUMBER)AS SEASONS
FROM EPISODE_INFORMATION
GROUP BY PARENTTCONST) A,RATINGS R
WHERE A.T_ID=R.TCONST) B,
TITLE_INFORMATION T
WHERE B.T_ID=T.TCONST
AND B.SEASONS=2
GROUP BY T.STARTYEAR,B.SEASONS
ORDER BY B.SEASONS ASC) M2,
(SELECT T.STARTYEAR AS SY3,B.SEASONS S3,ROUND(MAX(RATING),2) AS MAX_RATING_3,ROW_NUMBER() OVER(ORDER BY T.STARTYEAR ASC) AS rn  
FROM (SELECT A.SEASONS,A.T_ID,R.AVERAGERATING AS RATING FROM
(SELECT PARENTTCONST AS T_ID,COUNT(SEASONNUMBER)AS SEASONS
FROM EPISODE_INFORMATION
GROUP BY PARENTTCONST) A,RATINGS R
WHERE A.T_ID=R.TCONST) B,
TITLE_INFORMATION T
WHERE B.T_ID=T.TCONST
AND B.SEASONS=3
GROUP BY T.STARTYEAR,B.SEASONS
ORDER BY B.SEASONS ASC) M3,
(SELECT T.STARTYEAR AS SY4,B.SEASONS S4,ROUND(MAX(RATING),2) AS MAX_RATING_4,ROW_NUMBER() OVER(ORDER BY T.STARTYEAR ASC) AS rn 
FROM (SELECT A.SEASONS,A.T_ID,R.AVERAGERATING AS RATING FROM
(SELECT PARENTTCONST AS T_ID,COUNT(SEASONNUMBER)AS SEASONS
FROM EPISODE_INFORMATION
GROUP BY PARENTTCONST) A,RATINGS R
WHERE A.T_ID=R.TCONST) B,
TITLE_INFORMATION T
WHERE B.T_ID=T.TCONST
AND B.SEASONS=4
GROUP BY T.STARTYEAR,B.SEASONS
ORDER BY B.SEASONS ASC) M4,
(SELECT T.STARTYEAR AS SY5,B.SEASONS S5,ROUND(MAX(RATING),2) AS MAX_RATING_5,ROW_NUMBER() OVER(ORDER BY T.STARTYEAR ASC) AS rn 
FROM (SELECT A.SEASONS,A.T_ID,R.AVERAGERATING AS RATING FROM
(SELECT PARENTTCONST AS T_ID,COUNT(SEASONNUMBER)AS SEASONS
FROM EPISODE_INFORMATION
GROUP BY PARENTTCONST) A,RATINGS R
WHERE A.T_ID=R.TCONST) B,
TITLE_INFORMATION T
WHERE B.T_ID=T.TCONST
AND B.SEASONS=5
GROUP BY T.STARTYEAR,B.SEASONS
ORDER BY B.SEASONS ASC) M5,
(SELECT T.STARTYEAR AS SY20,B.SEASONS S20,ROUND(MAX(RATING),2) AS MAX_RATING_20,ROW_NUMBER() OVER(ORDER BY T.STARTYEAR ASC) AS rn  
FROM (SELECT A.SEASONS,A.T_ID,R.AVERAGERATING AS RATING FROM
(SELECT PARENTTCONST AS T_ID,COUNT(SEASONNUMBER)AS SEASONS
FROM EPISODE_INFORMATION
GROUP BY PARENTTCONST) A,RATINGS R
WHERE A.T_ID=R.TCONST) B,
TITLE_INFORMATION T
WHERE B.T_ID=T.TCONST
AND B.SEASONS=20
GROUP BY T.STARTYEAR,B.SEASONS
ORDER BY B.SEASONS ASC) M6
WHERE M1.rn=M2.rn
AND M1.rn=M3.rn
AND M1.rn=M4.rn
AND M1.rn=M5.rn
AND M1.rn=M6.rn


# QUERY3:

Display the highest rated TV shows along with the  number of episodes, number of writer, director, actor, actress and user input : year range 

SELECT PRIMARYTITLE , NUMBER_OF_EPISODES, DIRECTOR_COUNT, WRITER_COUNT
FROM(SELECT DISTINCT A.PRIMARYTITLE,B.NUMBER_OF_EPISODES,E.DIRECTOR_COUNT,E.WRITER_COUNT, A.GENRES,C.AVERAGERATING,D.NUMBER_OF_ACTORS,D.NUMBER_OF_ACTRESSES
FROM
(SELECT EP.PARENTTCONST,T.PRIMARYTITLE,T.GENRES
FROM EPISODE_INFORMATION EP,TITLE_INFORMATION T
WHERE EP.PARENTTCONST=T.TCONST
AND T.STARTYEAR>1990 AND T.STARTYEAR<2000) A
JOIN 
(SELECT PARENTTCONST,COUNT(TCONST) AS NUMBER_OF_EPISODES  
FROM EPISODE_INFORMATION
GROUP BY PARENTTCONST) B
ON A.PARENTTCONST=B.PARENTTCONST
JOIN
(SELECT TCONST,AVERAGERATING
FROM RATINGS
WHERE AVERAGERATING>5) C
ON B.PARENTTCONST=C.TCONST
JOIN 
(SELECT P1.TCONST,COUNT(DISTINCT P1.NCONST) NUMBER_OF_ACTORS,COUNT(DISTINCT P2.NCONST) NUMBER_OF_ACTRESSES
FROM PRINCIPAL_CREWINFO P1
INNER JOIN PRINCIPAL_CREWINFO P2 ON
P1.TCONST=P2.TCONST
WHERE P1.CATEGORY='actor' 
AND P2.CATEGORY='actress'
GROUP BY P1.TCONST) D
ON C.TCONST=D.TCONST
JOIN 
(SELECT TCONST,LENGTH(DIRECTORS) - LENGTH(REPLACE(DIRECTORS, ',', ''))+1 DIRECTOR_COUNT,
LENGTH(WRITERS) - LENGTH(REPLACE(WRITERS, ',', ''))+1 AS WRITER_COUNT
FROM TITLE_CREW) E
ON D.TCONST=E.TCONST
ORDER BY C.AVERAGERATING DESC)
WHERE ROWNUM<=10

                                                  
# QUERY4:

Line Graph - Display the percentage of male and female actors who have worked in any picture format which the user will select, arranged in the order of year range 1990-2005. The graph is showing us the trend of
working male and females in the industry.

SELECT T1.SY1,T1.ACTOR,ROUND(((T1.ACTOR_COUNT/T3.TOTAL)*100),2) AS PERCENT1,T2.SY2,T2.ACTRESS,ROUND(((T2.AVERAGE_RATING2/T3.TOTAL)*100),2) AS PERCENT2 FROM 
(SELECT T.STARTYEAR AS SY1,C.CATEGORY AS ACTOR,T.TITLETYPE,COUNT(C.NCONST) AS ACTOR_COUNT,ROW_NUMBER() OVER(ORDER BY T.STARTYEAR ASC) AS rn FROM
TITLE_INFORMATION T,
(SELECT P.NCONST,P.TCONST,P.CATEGORY,B.AVERAGERATING
FROM PRINCIPAL_CREWINFO P,
(SELECT TCONST,AVERAGERATING
FROM RATINGS) B
WHERE B.TCONST=P.TCONST
AND P.CATEGORY='actor') C
WHERE C.TCONST=T.TCONST
GROUP BY T.STARTYEAR,T.TITLETYPE,C.CATEGORY) T1,
(SELECT T.STARTYEAR AS SY2,C.CATEGORY AS ACTRESS,T.TITLETYPE,COUNT(C.NCONST) AS AVERAGE_RATING2,ROW_NUMBER() OVER(ORDER BY T.STARTYEAR ASC) AS rn FROM
TITLE_INFORMATION T,
(SELECT P.NCONST,P.TCONST,P.CATEGORY,B.AVERAGERATING
FROM PRINCIPAL_CREWINFO P,
(SELECT TCONST,AVERAGERATING
FROM RATINGS) B
WHERE B.TCONST=P.TCONST
AND P.CATEGORY='actress') C
WHERE C.TCONST=T.TCONST
GROUP BY T.STARTYEAR,T.TITLETYPE,C.CATEGORY) T2,
(SELECT T.STARTYEAR AS SY3,T.TITLETYPE,COUNT(C.NCONST) AS TOTAL,ROW_NUMBER() OVER(ORDER BY T.STARTYEAR ASC) AS rn FROM
TITLE_INFORMATION T,
(SELECT P.NCONST,P.TCONST,P.CATEGORY,B.AVERAGERATING
FROM PRINCIPAL_CREWINFO P,
(SELECT TCONST,AVERAGERATING
FROM RATINGS) B
WHERE B.TCONST=P.TCONST
AND P.CATEGORY IN ('actor','actress')) C
WHERE C.TCONST=T.TCONST
GROUP BY T.STARTYEAR,T.TITLETYPE) T3
WHERE T1.rn=T2.rn
AND T1.rn=T3.rn
AND T1.TITLETYPE='video'
AND T2.TITLETYPE='video'
AND T3.TITLETYPE='video';

# QUERY 5: 

Here is the data for line graph, where the average rating for famous picture types(movie,tvEpisode,short,video and video game) are arranged according to the rating received by the director in a year range of 1990-2005. There are 5 lines (movie,tvEpisode,short,video and video game) each showing a trend of ratings average rating received per year by a director. 

SELECT T1.S1,T1.TYPE1,T1.RATING1,T2.S2,T2.TYPE2,T2.RATING2,T3.S3,T3.TYPE3,T3.RATING3,T4.S4,T4.TYPE4,T4.RATING4,T5.S5,T5.TYPE5,T5.RATING5 FROM
(SELECT  V.STARTYEAR AS S1,V.TITLETYPE AS TYPE1,ROUND(AVG(V.AVERAGERATING),2) AS RATING1,ROW_NUMBER() OVER(ORDER BY V.STARTYEAR ASC) AS rn
FROM(SELECT C.NCONST,T.TITLETYPE,T.STARTYEAR,C.AVERAGERATING
FROM TITLE_INFORMATION T,
(SELECT P.NCONST,B.TCONST,B.AVERAGERATING
FROM PRINCIPAL_CREWINFO P,(SELECT TCONST,AVERAGERATING
FROM RATINGS) B
WHERE P.TCONST=B.TCONST
AND P.CATEGORY='director')C
WHERE T.TCONST=C.TCONST
AND T.STARTYEAR>1990
AND T.TITLETYPE='movie') V,PERSONAL_INFORMATION P
WHERE V.NCONST=P.NCONST
GROUP BY V.STARTYEAR,V.TITLETYPE) T1,
(SELECT  V.STARTYEAR AS S2,V.TITLETYPE AS TYPE2,ROUND(AVG(V.AVERAGERATING),2) AS RATING2,ROW_NUMBER() OVER(ORDER BY V.STARTYEAR ASC) AS rn
FROM(SELECT C.NCONST,T.TITLETYPE,T.STARTYEAR,C.AVERAGERATING
FROM TITLE_INFORMATION T,
(SELECT P.NCONST,B.TCONST,B.AVERAGERATING
FROM PRINCIPAL_CREWINFO P,(SELECT TCONST,AVERAGERATING
FROM RATINGS) B
WHERE P.TCONST=B.TCONST
AND P.CATEGORY='director')C
WHERE T.TCONST=C.TCONST
AND T.STARTYEAR>1990
AND T.TITLETYPE='tvEpisode') V,PERSONAL_INFORMATION P
WHERE V.NCONST=P.NCONST
GROUP BY V.STARTYEAR,V.TITLETYPE) T2,
(SELECT  V.STARTYEAR AS S3,V.TITLETYPE AS TYPE3,ROUND(AVG(V.AVERAGERATING),2) AS RATING3,ROW_NUMBER() OVER(ORDER BY V.STARTYEAR ASC) AS rn
FROM(SELECT C.NCONST,T.TITLETYPE,T.STARTYEAR,C.AVERAGERATING
FROM TITLE_INFORMATION T,
(SELECT P.NCONST,B.TCONST,B.AVERAGERATING
FROM PRINCIPAL_CREWINFO P,(SELECT TCONST,AVERAGERATING
FROM RATINGS) B
WHERE P.TCONST=B.TCONST
AND P.CATEGORY='director')C
WHERE T.TCONST=C.TCONST
AND T.STARTYEAR>1990
AND T.TITLETYPE='short') V,PERSONAL_INFORMATION P
WHERE V.NCONST=P.NCONST
GROUP BY V.STARTYEAR,V.TITLETYPE) T3,
(SELECT  V.STARTYEAR AS S4,V.TITLETYPE AS TYPE4,ROUND(AVG(V.AVERAGERATING),2) AS RATING4,ROW_NUMBER() OVER(ORDER BY V.STARTYEAR ASC) AS rn
FROM(SELECT C.NCONST,T.TITLETYPE,T.STARTYEAR,C.AVERAGERATING
FROM TITLE_INFORMATION T,
(SELECT P.NCONST,B.TCONST,B.AVERAGERATING
FROM PRINCIPAL_CREWINFO P,(SELECT TCONST,AVERAGERATING
FROM RATINGS) B
WHERE P.TCONST=B.TCONST
AND P.CATEGORY='director')C
WHERE T.TCONST=C.TCONST
AND T.STARTYEAR>1990
AND T.TITLETYPE='video') V,PERSONAL_INFORMATION P
WHERE V.NCONST=P.NCONST
GROUP BY V.STARTYEAR,V.TITLETYPE) T4,
(SELECT  V.STARTYEAR AS S5,V.TITLETYPE AS TYPE5,ROUND(AVG(V.AVERAGERATING),2) AS RATING5,ROW_NUMBER() OVER(ORDER BY V.STARTYEAR ASC) AS rn
FROM(SELECT C.NCONST,T.TITLETYPE,T.STARTYEAR,C.AVERAGERATING
FROM TITLE_INFORMATION T,
(SELECT P.NCONST,B.TCONST,B.AVERAGERATING
FROM PRINCIPAL_CREWINFO P,(SELECT TCONST,AVERAGERATING
FROM RATINGS) B
WHERE P.TCONST=B.TCONST
AND P.CATEGORY='director')C
WHERE T.TCONST=C.TCONST
AND T.STARTYEAR>1990
AND T.TITLETYPE='videoGame') V,PERSONAL_INFORMATION P
WHERE V.NCONST=P.NCONST
GROUP BY V.STARTYEAR,V.TITLETYPE) T5
WHERE T1.rn=T2.rn
AND T1.rn=T3.rn
AND T1.rn=T4.rn
AND T1.rn=T5.rn;

# QUERY 6:

Display a Bar Graph for 4 lines(movie,tvMovie,tvEpisode,video) with average rating on y axis and run time on x axis. To compare the trend of ratings received on the basis of length of these popular picture formats. 

SELECT CT.RUNTIME1,CT.MOVIE,CT.AVERAGE_RATING1,CT.RUNTIME2,CT.TVMOVIE,CT.AVERAGE_RATING2,CT.RUNTIME3,CT.TVEPISODE,CT.AVERAGE_RATING3,
CT.RUNTIME4,CT.VIDEO,CT.AVERAGE_RATING4 FROM
(
SELECT MS1.RUNTIME1,MS1.MOVIE,MS1.AVERAGE_RATING1,MS1.RUNTIME2,MS1.TVMOVIE,MS1.AVERAGE_RATING2,MS1.RUNTIME3,MS1.TVEPISODE,MS1.AVERAGE_RATING3,
MS1.RUNTIME4,MS1.VIDEO,MS1.AVERAGE_RATING4 FROM
(SELECT * FROM
(SELECT B.RUNTIMEMINUTES AS RUNTIME1,B.TITLETYPE AS MOVIE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING1,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='movie'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=25) T1,
(SELECT B.RUNTIMEMINUTES AS RUNTIME2,B.TITLETYPE AS TVMOVIE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING2,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='tvMovie'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=25) T2,
(SELECT B.RUNTIMEMINUTES AS RUNTIME3,B.TITLETYPE AS TVEPISODE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING3,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='tvEpisode'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=25) T3,
(SELECT B.RUNTIMEMINUTES AS RUNTIME4,B.TITLETYPE AS VIDEO,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING4,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='video'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=25) T4
WHERE T1.rn=T2.rn
AND T1.rn=T3.rn
AND T1.rn=T4.rn) MS1 
UNION
SELECT MS2.RUNTIME1,MS2.MOVIE,MS2.AVERAGE_RATING1,MS2.RUNTIME2,MS2.TVMOVIE,MS2.AVERAGE_RATING2,MS2.RUNTIME3,MS2.TVEPISODE,MS2.AVERAGE_RATING3,
MS2.RUNTIME4,MS2.VIDEO,MS2.AVERAGE_RATING4 FROM
(SELECT * FROM
(SELECT B.RUNTIMEMINUTES AS RUNTIME1,B.TITLETYPE AS MOVIE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING1,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='movie'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=60) T1,
(SELECT B.RUNTIMEMINUTES AS RUNTIME2,B.TITLETYPE AS TVMOVIE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING2,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='tvMovie'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=60) T2,
(SELECT B.RUNTIMEMINUTES AS RUNTIME3,B.TITLETYPE AS TVEPISODE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING3,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='tvEpisode'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=60) T3,
(SELECT B.RUNTIMEMINUTES AS RUNTIME4,B.TITLETYPE AS VIDEO,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING4,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='video'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=60) T4
WHERE T1.rn=T2.rn
AND T1.rn=T3.rn
AND T1.rn=T4.rn) MS2
UNION
SELECT MS3.RUNTIME1,MS3.MOVIE,MS3.AVERAGE_RATING1,MS3.RUNTIME2,MS3.TVMOVIE,MS3.AVERAGE_RATING2,MS3.RUNTIME3,MS3.TVEPISODE,MS3.AVERAGE_RATING3,
MS3.RUNTIME4,MS3.VIDEO,MS3.AVERAGE_RATING4 FROM
(SELECT * FROM
(SELECT B.RUNTIMEMINUTES AS RUNTIME1,B.TITLETYPE AS MOVIE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING1,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='movie'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=120) T1,
(SELECT B.RUNTIMEMINUTES AS RUNTIME2,B.TITLETYPE AS TVMOVIE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING2,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='tvMovie'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=120) T2,
(SELECT B.RUNTIMEMINUTES AS RUNTIME3,B.TITLETYPE AS TVEPISODE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING3,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='tvEpisode'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=120) T3,
(SELECT B.RUNTIMEMINUTES AS RUNTIME4,B.TITLETYPE AS VIDEO,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING4,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='video'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=120) T4
WHERE T1.rn=T2.rn
AND T1.rn=T3.rn
AND T1.rn=T4.rn) MS3
UNION
SELECT MS4.RUNTIME1,MS4.MOVIE,MS4.AVERAGE_RATING1,MS4.RUNTIME2,MS4.TVMOVIE,MS4.AVERAGE_RATING2,MS4.RUNTIME3,MS4.TVEPISODE,MS4.AVERAGE_RATING3,
MS4.RUNTIME4,MS4.VIDEO,MS4.AVERAGE_RATING4 FROM
(SELECT * FROM
(SELECT B.RUNTIMEMINUTES AS RUNTIME1,B.TITLETYPE AS MOVIE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING1,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='movie'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=180) T1,
(SELECT B.RUNTIMEMINUTES AS RUNTIME2,B.TITLETYPE AS TVMOVIE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING2,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='tvMovie'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=180) T2,
(SELECT B.RUNTIMEMINUTES AS RUNTIME3,B.TITLETYPE AS TVEPISODE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING3,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='tvEpisode'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=180) T3,
(SELECT B.RUNTIMEMINUTES AS RUNTIME4,B.TITLETYPE AS VIDEO,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING4,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='video'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=180) T4
WHERE T1.rn=T2.rn
AND T1.rn=T3.rn
AND T1.rn=T4.rn) MS4
UNION
SELECT MS5.RUNTIME1,MS5.MOVIE,MS5.AVERAGE_RATING1,MS5.RUNTIME2,MS5.TVMOVIE,MS5.AVERAGE_RATING2,MS5.RUNTIME3,MS5.TVEPISODE,MS5.AVERAGE_RATING3,
MS5.RUNTIME4,MS5.VIDEO,MS5.AVERAGE_RATING4 FROM
(SELECT * FROM
(SELECT B.RUNTIMEMINUTES AS RUNTIME1,B.TITLETYPE AS MOVIE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING1,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='movie'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=240) T1,
(SELECT B.RUNTIMEMINUTES AS RUNTIME2,B.TITLETYPE AS TVMOVIE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING2,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='tvMovie'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=240) T2,
(SELECT B.RUNTIMEMINUTES AS RUNTIME3,B.TITLETYPE AS TVEPISODE,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING3,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='tvEpisode'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=240) T3,
(SELECT B.RUNTIMEMINUTES AS RUNTIME4,B.TITLETYPE AS VIDEO,ROUND(AVG(R.AVERAGERATING),2) AS AVERAGE_RATING4,
ROW_NUMBER() OVER(ORDER BY B.RUNTIMEMINUTES ASC) AS rn  FROM
RATINGS R,(SELECT T.RUNTIMEMINUTES,T.TCONST,T.TITLETYPE
FROM TITLE_INFORMATION T
WHERE  T.STARTYEAR>1990
AND T.ENDYEAR<2000
AND T.TITLETYPE='video'
AND T.TITLETYPE NOT IN ('videoGame','tvSpecial','tvEpisode','tvShort','tvMovie','tvMiniSeries')) B
WHERE B.TCONST=R.TCONST
GROUP BY B.RUNTIMEMINUTES,B.TITLETYPE
HAVING B.RUNTIMEMINUTES=240) T4
WHERE T1.rn=T2.rn
AND T1.rn=T3.rn
AND T1.rn=T4.rn) MS5) CT;

# QUERY 7:

Display a Bar Graph for the top 5 countries which have produced the highest number of titles in the range of years 1990-2005; 
the user can select the range of year.

SELECT TOP5.S1,TOP5.R1,TOP5.TITLE_PRODUCED1,TOP5.S2,TOP5.R2,TOP5.TITLE_PRODUCED2,TOP5.S3,TOP5.R3,TOP5.TITLE_PRODUCED3,
TOP5.S4,TOP5.R4,TOP5.TITLE_PRODUCED4,TOP5.S5,TOP5.R5,TOP5.TITLE_PRODUCED5 FROM
(SELECT US.S1,US.R1,US.TITLE_PRODUCED1,GB.S2,GB.R2,GB.TITLE_PRODUCED2,JP.S3,JP.R3,JP.TITLE_PRODUCED3,GR.S4,GR.R4,GR.TITLE_PRODUCED4,
FR.S5,FR.R5,FR.TITLE_PRODUCED5 FROM
(SELECT TI1.STARTYEAR AS S1,T1.REGION AS R1,COUNT(T1.REGION) AS TITLE_PRODUCED1,ROW_NUMBER() OVER(ORDER BY TI1.STARTYEAR ASC) AS rn FROM
TITLE T1,TITLE_INFORMATION TI1
WHERE TI1.STARTYEAR>1990
AND T1.TITLEID=TI1.TCONST
AND T1.REGION='US'
GROUP BY TI1.STARTYEAR,T1.REGION) US,
(SELECT TI1.STARTYEAR AS S2,T1.REGION AS R2,COUNT(T1.REGION) AS TITLE_PRODUCED2,ROW_NUMBER() OVER(ORDER BY TI1.STARTYEAR ASC) AS rn FROM
TITLE T1,TITLE_INFORMATION TI1
WHERE TI1.STARTYEAR>1990
AND T1.TITLEID=TI1.TCONST
AND T1.REGION='GB'
GROUP BY TI1.STARTYEAR,T1.REGION) GB,
(SELECT TI1.STARTYEAR AS S3,T1.REGION AS R3,COUNT(T1.REGION) AS TITLE_PRODUCED3,ROW_NUMBER() OVER(ORDER BY TI1.STARTYEAR ASC) AS rn FROM
TITLE T1,TITLE_INFORMATION TI1
WHERE TI1.STARTYEAR>1990
AND T1.TITLEID=TI1.TCONST
AND T1.REGION='JP'
GROUP BY TI1.STARTYEAR,T1.REGION) JP,
(SELECT TI1.STARTYEAR AS S4,T1.REGION AS R4,COUNT(T1.REGION) AS TITLE_PRODUCED4,ROW_NUMBER() OVER(ORDER BY TI1.STARTYEAR ASC) AS rn FROM
TITLE T1,TITLE_INFORMATION TI1
WHERE TI1.STARTYEAR>1990
AND T1.TITLEID=TI1.TCONST
AND T1.REGION='GR'
GROUP BY TI1.STARTYEAR,T1.REGION) GR,
(SELECT TI1.STARTYEAR AS S5,T1.REGION AS R5,COUNT(T1.REGION) TITLE_PRODUCED5,ROW_NUMBER() OVER(ORDER BY TI1.STARTYEAR ASC) AS rn FROM
TITLE T1,TITLE_INFORMATION TI1
WHERE TI1.STARTYEAR>1990
AND T1.TITLEID=TI1.TCONST
AND T1.REGION='FR'
GROUP BY TI1.STARTYEAR,T1.REGION) FR
WHERE US.rn=GB.rn
AND US.rn=JP.rn
AND US.rn=GR.rn
AND US.rn=FR.rn
AND US.S1>1990
AND US.S1<2005
AND GB.S2>1990
AND GB.S2<2005
AND JP.S3>1990
AND JP.S3<2005
AND GR.S4>1990
AND GR.S4<2005
AND FR.S5>1990
AND FR.S5<2005) TOP5;


# QUERY8:

Display Graph for the top 10 languages in which movies,tvSeries,videos etc. are made and produced in. As the english language has the majority of picture formats being produced in, therefore we look at languages other
than the 'english' language.  

SELECT LT.S1,LT.L1,LT.C1,LT.R1,LT.S2,LT.L2,LT.C2,LT.R2,LT.S3,LT.L3,LT.C3,LT.R3,LT.S4,LT.L4,LT.C4,LT.R4,LT.S5,LT.L5,LT.C5,LT.R5,
LT.S6,LT.L6,LT.C6,LT.R6,LT.S7,LT.L7,LT.C7,LT.R7,LT.S8,LT.L8,LT.C8,LT.R8,LT.S9,LT.L9,LT.C9,LT.R9,LT.S10,LT.L10,LT.C10,LT.R10
FROM
(SELECT * FROM
(SELECT A.STARTYEAR AS S1,A.LANGUAGE AS L1,COUNT(A.TCONST) AS C1,ROUND(MAX(R.AVERAGERATING),2) AS R1,
ROW_NUMBER() OVER(ORDER BY A.STARTYEAR ASC) rn FROM
(SELECT TI.STARTYEAR,B.LANGUAGE,TI.TCONST FROM
(SELECT T.LANGUAGE,T.TITLEID FROM 
TITLE T
WHERE LANGUAGE<>'n/a'
AND LANGUAGE<>'en') B,
TITLE_INFORMATION TI
WHERE B.TITLEID=TI.TCONST) A,RATINGS R
WHERE A.TCONST=R.TCONST
AND A.STARTYEAR>1990
AND A.LANGUAGE='Bulgarian'
GROUP BY A.STARTYEAR,A.LANGUAGE) BG,
(SELECT A.STARTYEAR AS S2,A.LANGUAGE AS L2,COUNT(A.TCONST) AS C2,ROUND(MAX(R.AVERAGERATING),2) AS R2,
ROW_NUMBER() OVER(ORDER BY A.STARTYEAR ASC) rn FROM
(SELECT TI.STARTYEAR,B.LANGUAGE,TI.TCONST FROM
(SELECT T.LANGUAGE,T.TITLEID FROM 
TITLE T
WHERE LANGUAGE<>'n/a'
AND LANGUAGE<>'en') B,
TITLE_INFORMATION TI
WHERE B.TITLEID=TI.TCONST) A,RATINGS R
WHERE A.TCONST=R.TCONST
AND A.STARTYEAR>1990
AND A.LANGUAGE='French'
GROUP BY A.STARTYEAR,A.LANGUAGE) FR,
(SELECT A.STARTYEAR AS S3,A.LANGUAGE AS L3,COUNT(A.TCONST) AS C3,ROUND(MAX(R.AVERAGERATING),2) AS R3,
ROW_NUMBER() OVER(ORDER BY A.STARTYEAR ASC) rn FROM
(SELECT TI.STARTYEAR,B.LANGUAGE,TI.TCONST FROM
(SELECT T.LANGUAGE,T.TITLEID FROM 
TITLE T
WHERE LANGUAGE<>'n/a'
AND LANGUAGE<>'en') B,
TITLE_INFORMATION TI
WHERE B.TITLEID=TI.TCONST) A,RATINGS R
WHERE A.TCONST=R.TCONST
AND A.STARTYEAR>1990
AND A.LANGUAGE='Turkish'
GROUP BY A.STARTYEAR,A.LANGUAGE) TR,
(SELECT A.STARTYEAR AS S4,A.LANGUAGE AS L4,COUNT(A.TCONST) AS C4,ROUND(MAX(R.AVERAGERATING),2) AS R4,
ROW_NUMBER() OVER(ORDER BY A.STARTYEAR ASC) rn FROM
(SELECT TI.STARTYEAR,B.LANGUAGE,TI.TCONST FROM
(SELECT T.LANGUAGE,T.TITLEID FROM 
TITLE T
WHERE LANGUAGE<>'n/a'
AND LANGUAGE<>'en') B,
TITLE_INFORMATION TI
WHERE B.TITLEID=TI.TCONST) A,RATINGS R
WHERE A.TCONST=R.TCONST
AND A.STARTYEAR>1990
AND A.LANGUAGE='Hebrew'
GROUP BY A.STARTYEAR,A.LANGUAGE) HE,
(SELECT A.STARTYEAR AS S5,A.LANGUAGE AS L5,COUNT(A.TCONST) AS C5,ROUND(MAX(R.AVERAGERATING),2) AS R5,
ROW_NUMBER() OVER(ORDER BY A.STARTYEAR ASC) rn FROM
(SELECT TI.STARTYEAR,B.LANGUAGE,TI.TCONST FROM
(SELECT T.LANGUAGE,T.TITLEID FROM 
TITLE T
WHERE LANGUAGE<>'n/a'
AND LANGUAGE<>'en') B,
TITLE_INFORMATION TI
WHERE B.TITLEID=TI.TCONST) A,RATINGS R
WHERE A.TCONST=R.TCONST
AND A.STARTYEAR>1990
AND A.LANGUAGE='Spanish'
GROUP BY A.STARTYEAR,A.LANGUAGE) SP,
(SELECT A.STARTYEAR AS S6,A.LANGUAGE AS L6,COUNT(A.TCONST) AS C6,ROUND(MAX(R.AVERAGERATING),2) AS R6,
ROW_NUMBER() OVER(ORDER BY A.STARTYEAR ASC) rn FROM
(SELECT TI.STARTYEAR,B.LANGUAGE,TI.TCONST FROM
(SELECT T.LANGUAGE,T.TITLEID FROM 
TITLE T
WHERE LANGUAGE<>'n/a'
AND LANGUAGE<>'en') B,
TITLE_INFORMATION TI
WHERE B.TITLEID=TI.TCONST) A,RATINGS R
WHERE A.TCONST=R.TCONST
AND A.STARTYEAR>1990
AND A.LANGUAGE='TraditionalChinese'
GROUP BY A.STARTYEAR,A.LANGUAGE) TC,
(SELECT A.STARTYEAR AS S7,A.LANGUAGE AS L7,COUNT(A.TCONST) AS C7,ROUND(MAX(R.AVERAGERATING),2) AS R7,
ROW_NUMBER() OVER(ORDER BY A.STARTYEAR ASC) rn FROM
(SELECT TI.STARTYEAR,B.LANGUAGE,TI.TCONST FROM
(SELECT T.LANGUAGE,T.TITLEID FROM 
TITLE T
WHERE LANGUAGE<>'n/a'
AND LANGUAGE<>'en') B,
TITLE_INFORMATION TI
WHERE B.TITLEID=TI.TCONST) A,RATINGS R
WHERE A.TCONST=R.TCONST
AND A.STARTYEAR>1990
AND A.LANGUAGE='MandarinChinese'
GROUP BY A.STARTYEAR,A.LANGUAGE) MC,
(SELECT A.STARTYEAR AS S8,A.LANGUAGE AS L8,COUNT(A.TCONST) AS C8,ROUND(MAX(R.AVERAGERATING),2) AS R8,
ROW_NUMBER() OVER(ORDER BY A.STARTYEAR ASC) rn FROM
(SELECT TI.STARTYEAR,B.LANGUAGE,TI.TCONST FROM
(SELECT T.LANGUAGE,T.TITLEID FROM 
TITLE T
WHERE LANGUAGE<>'n/a'
AND LANGUAGE<>'en') B,
TITLE_INFORMATION TI
WHERE B.TITLEID=TI.TCONST) A,RATINGS R
WHERE A.TCONST=R.TCONST
AND A.STARTYEAR>1990
AND A.LANGUAGE='Catalan'
GROUP BY A.STARTYEAR,A.LANGUAGE) CA,
(SELECT A.STARTYEAR AS S9,A.LANGUAGE AS L9,COUNT(A.TCONST) AS C9,ROUND(MAX(R.AVERAGERATING),2) AS R9,
ROW_NUMBER() OVER(ORDER BY A.STARTYEAR ASC) rn FROM
(SELECT TI.STARTYEAR,B.LANGUAGE,TI.TCONST FROM
(SELECT T.LANGUAGE,T.TITLEID FROM 
TITLE T
WHERE LANGUAGE<>'n/a'
AND LANGUAGE<>'en') B,
TITLE_INFORMATION TI
WHERE B.TITLEID=TI.TCONST) A,RATINGS R
WHERE A.TCONST=R.TCONST
AND A.STARTYEAR>1990
AND A.LANGUAGE='Tagalog'
GROUP BY A.STARTYEAR,A.LANGUAGE) TL,
(SELECT A.STARTYEAR AS S10,A.LANGUAGE AS L10,COUNT(A.TCONST) AS C10,ROUND(MAX(R.AVERAGERATING),2) AS R10,
ROW_NUMBER() OVER(ORDER BY A.STARTYEAR ASC) rn FROM
(SELECT TI.STARTYEAR,B.LANGUAGE,TI.TCONST FROM
(SELECT T.LANGUAGE,T.TITLEID FROM 
TITLE T
WHERE LANGUAGE<>'n/a'
AND LANGUAGE<>'en') B,
TITLE_INFORMATION TI
WHERE B.TITLEID=TI.TCONST) A,RATINGS R
WHERE A.TCONST=R.TCONST
AND A.STARTYEAR>1990
AND A.LANGUAGE='Bulgarian'
GROUP BY A.STARTYEAR,A.LANGUAGE) FA
WHERE BG.rn=FR.rn
AND BG.rn=TR.rn
AND BG.rn=HE.rn
AND BG.rn=SP.rn
AND BG.rn=TC.rn
AND BG.rn=MC.rn
AND BG.rn=CA.rn
AND BG.rn=TL.rn
AND BG.rn=FA.rn) LT
